{% set python_min = "3.9" %}
{% set version = "4.0.0" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://github.com/descarteslabs/descarteslabs-python/archive/v{{ version }}.tar.gz
  sha256: 4ca2e6e07957e5a5bd4fb7a03199ee6c5c596124069eaacf1c80dc1268983bda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - descarteslabs = descarteslabs._dl_modules.client.scripts.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - blosc >=1.11.2
    - python >={{ python_min }}
    - affine >=2.2.2
    - cachetools >=3.1.1
    - dill >=0.3.6
    - dynaconf >=3.1.11
    - geojson >=2.5.0
    - geopandas >=0.13.2
    - imagecodecs >=2023.3.16
    - lazy-object-proxy >=1.7.1
    - mercantile >=1.1.3
    - numpy >=1.23.2
    - pillow >=9.2.0
    - pyarrow >=14.0.1
    - pydantic >=2.4.0
    - python-blosc >=1.11.2
    - pytz >=2021.1
    - requests >=2.32.3,<3
    - setuptools >=70.0.0
    - shapely >=2.0.0
    - strenum >=0.4.8
    - tifffile >=2023.9.26
    - tqdm >=4.66.3
    - urllib3 >=1.26.19,!=2.0.0,!=2.0.1,!=2.0.2,!=2.0.3,!=2.0.4

test:
  source_files:
    - .
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - mock
    - hypothesis ==5.7.0
    - responses
    # optional
    - matplotlib-base >=3.0.3
    - ipyleaflet >=0.13.1,<1
    - ipywidgets >=7.5.1,<8
    # - ibis-framework ==1.4.0
    # AttributeError: module 'sqlalchemy' has no attribute 'Binary'
    - sqlalchemy <1.4
    - geopandas >=0.10.2
    # - traitlets >=4.3.3,<5
    - freezegun
  commands:
    # - pip check
    # need to figure out the login tests that must be skipped.
    # - pytest -rfExXP --assert=plain --ignore-glob="*/smoke_tests" --ignore-glob="*/e2e" --ignore="descarteslabs/third_party/" --ignore=descarteslabs/_dl_modules/scenes/tests/{test_scene.py,test_scenecollection.py} --ignore=descarteslabs/_dl_modules/workflows/models/tests/{test_job.py,test_published_graft.py,test_tile_url.py} descarteslabs 
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Descartes Labs Python Library

extra:
  recipe-maintainers:
    - ocefpaf
