{% set version = "2.1.2" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://github.com/descarteslabs/descarteslabs-python/archive/v{{ version }}.tar.gz
  sha256: b376408864c242512083e640127195c4aa352ece4aac544aabda14aa94d6862a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - descarteslabs = descarteslabs._dl_modules.client.scripts.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - blosc >=1.10.6
    - python >=3.7
    - affine >=2.2.2
    - python-blosc >=1.10.6
    - cachetools >=3.1.1
    - dill >=0.3.6
    - dynaconf >=3.1.11
    - geojson >=2.5.0
    - grpcio >=1.35.0,<2
    - imagecodecs >=2021.5.20
    - lazy-object-proxy >=1.7.1
    - mercantile >=1.1.3
    - numpy >=1.21.6,<1.23.0
    - pillow >=9.2.0
    - protobuf >=3.19.0,<4
    - pyarrow >=3.0.0
    - pytz >=2021.1
    # requests [security]
    - pyopenssl
    - cryptography
    - requests >=2.28.1,<3
    - setuptools >=65.6.3
    - shapely >=1.8.1
    - strenum >=0.4.8
    - tifffile ==2021.4.8
    - tqdm >=4.32.1
    - urllib3 >=1.26.12,<2

test:
  source_files:
    - .
  requires:
    - pip
    - pytest
    - mock
    - hypothesis ==5.7.0
    - responses
    # optional
    - matplotlib-base >=3.0.3
    - ipyleaflet >=0.13.1,<1
    - ipywidgets >=7.5.1,<8
    - ibis-framework ==1.4.0
    # AttributeError: module 'sqlalchemy' has no attribute 'Binary'
    - sqlalchemy <1.4
    - geopandas >=0.10.2
    # - traitlets >=4.3.3,<5
    - freezegun
  commands:
    # - pip check
    # need to figure out the login tests that must be skipped.
    # - pytest -rfExXP --assert=plain --ignore-glob="*/smoke_tests" --ignore-glob="*/e2e" --ignore="descarteslabs/third_party/" --ignore=descarteslabs/_dl_modules/scenes/tests/{test_scene.py,test_scenecollection.py} --ignore=descarteslabs/_dl_modules/workflows/models/tests/{test_job.py,test_published_graft.py,test_tile_url.py} descarteslabs 
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Descartes Labs Python Library

extra:
  recipe-maintainers:
    - ocefpaf
