{% set version = "1.4.0" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/descarteslabs/descarteslabs-{{ version }}.tar.gz
  sha256: 82eda26e0be5ef9a4517e48d8d245e2a73cc82d33a0293448d779a9909d47876

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - descarteslabs = descarteslabs.client.scripts.__main__:main

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - affine >=2.2.1
    - cachetools >=2.0.1
    - cloudpickle ==0.4.0
    - geojson >=2.5.0
    - grpcio >=1.16.1,<2
    - protobuf ==3.11.2,<4
    - numpy >=1.17.4
    - pyarrow
    - pytz >=2019.1
    # requests [security]
    - pyopenssl
    - cryptography
    - requests >=2.20.1,<3
    - six >=1.12.0
    - shapely >=1.6.3,<2

test:
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Descartes Labs Python Library

extra:
  recipe-maintainers:
    - ocefpaf
