{% set version = "1.11.0" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://github.com/descarteslabs/descarteslabs-python/archive/v{{ version }}.tar.gz
  sha256: 39f2dd99d50df30e2e0f9a552650f983813e6119a628f3c8e666308f8fca7184

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - descarteslabs = descarteslabs._dl_modules.client.scripts.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - affine >=2.2.2
    - python-blosc ==1.10.6
    - cachetools >=3.1.1
    - cloudpickle ==1.6.0
    - dynaconf ==3.1.1
    - geojson >=2.5.0
    - grpcio >=1.35.0,<2
    - imagecodecs >=2021.5.20
    - lazy-object-proxy >=1.7.1
    - mercantile >=1.1.3
    - numpy >=1.21.6,<1.23.0
    - pillow >=8.2.0
    - protobuf >=3.19.0,<4
    - pyarrow >=3.0.0
    - pytz >=2021.1
    # requests [security]
    - pyopenssl
    - cryptography
    - requests >=2.27.1,<3
    - six >=1.15.0
    - shapely >=1.8.1,<2
    - tifffile ==2021.4.8
    - tqdm >=4.32.1

test:
  requires:
    - pip
    - pytest
    - mock
    - hypothesis ==5.7.0
    - responses
    # optional
    - matplotlib-base >=3.0.3
    - ipyleaflet >=0.13.1,<1
    - ipywidgets >=7.5.1,<8
    # - traitlets >=4.3.3,<5
    - freezegun
  commands:
    - pip check
    # The first two are smoke tests skipped upstream, the last two required a login token.
    - pytest -rfExXP --assert=plain --ignore-glob="*/smoke_tests" --ignore="descarteslabs/third_party/" --pyargs descarteslabs -k "not (test_metadata.py or test_raster.py or test_places_find or test_auth_login or test_coverage or test_fork_from_fork or test_wrapper_process or  test_wrapper_unused_in_main_process)"
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Descartes Labs Python Library

extra:
  recipe-maintainers:
    - ocefpaf
