{% set version = "1.5.0" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://github.com/descarteslabs/descarteslabs-python/archive/v{{ version }}.tar.gz
  sha256: 29eb6f6579f2d772e058382b667d5506012f235e6c892277b8572909d5a845d4

build:
  number: 1
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - descarteslabs = descarteslabs.client.scripts.__main__:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - affine >=2.2.1
    - backports-datetime-fromisoformat >=1.0.0  # [py<37]
    - cachetools >=2.0.1
    - cloudpickle ==0.4.0  # [py<38]
    - cloudpickle ==1.6.0  # [py>=38]
    - geojson >=2.5.0
    - grpcio >=1.16.1,<2
    - protobuf >=3.11.2,<4
    - numpy >=1.17.4
    - pyarrow >=0.17.1,<1
    - pytz >=2019.1
    # requests [security]
    - pyopenssl
    - cryptography
    - requests >=2.20.1,<3
    - six >=1.12.0
    - shapely >=1.6.3,<2

test:
  requires:
    - mock
    - python-blosc
    - pytest
    - responses
    - hypothesis
    - mercantile
  commands:
    # The first two are smoke tests skipped upstream, the last two required a login token.
    - pytest --pyargs descarteslabs -k "not (test_metadata.py or test_raster.py or test_places_find or test_auth_login)"
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Descartes Labs Python Library

extra:
  recipe-maintainers:
    - ocefpaf
