travis:
  secure:
    BINSTAR_TOKEN: V4YmavvzCRqVojgQU3Mnxc3aknBDdPYn4OtTSesCjZIAb+NAeXbHZs0mdBj5+MvX6i6Wz8Y9UL5S9JqnIvESSNqgOkvLwW4Wx7VtOTAWCeZUo0U0NTL47If0z5U9EsH1JkDHoj4Ze90PHRhodAxgwNDWlZtmFK9SNPNRLLLQsqATpH/Q2ZeV6iwZYmf9hKGC8iAjaJBOMI58vIaf/eyeE8coBZQLB2pLPYQwnsVemcqIzW616EgQe9WR+rv+0inippFLZmtacCoFLaor32swK8V0j3tjvLeUNuECg9PGIGzdNIuRm6/puh0GVhIPVLqu7omBFHBZcUKz/N7kYTbrFy2hV7lxKicgoU4PaRynqGXhd/1b1FQRAO3bVC9eMCMYAjVj4OxYS7FoO/R4EjV76qCXiMRNrYRMNv/ez51CvlObWgXFXacQJx69doplKqW9ZCzax5nbPRhdPQpWBuQ/ttkHBCNJK9UFwitZbLCxRaZV8vp+JnweV2X+eQcwmqHeP91OhiODjAZmbM2QAziM8NVE1hbnDEaAEHhkSqrQ+zkwXUujFaYMw/V2c3fY7j9KkF+B0927IhY82ZT8aMI6rHVtweRmSH1tRuGkLsFvNVvYuTgGJi5nNcZpmD4r9cxSyvZdT9eTaON24x+YlQIdzSe4RmiJFPf/iP9726Z8bGM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
